---
deployment:
  targets:
    production:
      domain: example.com
      path: /
      restart_app: false
      pre_build:
        commands:
          - "git reset --hard HEAD"
          - "git clean -fd"
      build:
        commands:
          - "composer install --no-dev"
      post_deploy:
        commands:
          - "php setup_admin.php"
